version: 2

jobs:
  build:
    docker:
      - image: yokogawa/ansible-lint
      - image: python:3.7
    working_directory: ~/isucon/

    steps:
      - checkout

      - run:
          name: Run ansible lint
          command: git ls-files -z provisioning/*.yml | xargs -0 -r ansible-lint --force-color -x ANSIBLE0016
      
      - run:
          name: Benchmark script
          command: bench/python3 bench.py 10